import type {
  GuestContactLog,
  GuestEvent,
  GuestGift,
  GuestLoan,
  GuestNote,
  GuestPerson,
  GuestPersonTag,
  GuestReminder,
  GuestState,
  GuestTag,
} from "./types"

function uid(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID()
  }
  return Math.random().toString(36).slice(2) + Date.now().toString(36)
}

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86_400_000).toISOString()
}

function daysAhead(n: number): string {
  return new Date(Date.now() + n * 86_400_000).toISOString()
}

interface PersonSpec {
  name: string
  nickname?: string | null
  gender: "female" | "male"
  profile_index: number
  avatar_bg: number
  relationship_type: GuestPerson["relationship_type"]
  phone_number?: string | null
  kakao_nickname?: string | null
  instagram_handle?: string | null
  birth: [number, number, number] | null
  mbti?: string | null
  food_preference?: string | null
  how_we_met?: string | null
  memo?: string | null
  reminder_interval_days: number
  last_contact_days_ago: number | null
  tagSlugs: string[]
}

const TAG_SPECS: { slug: string; name: string }[] = [
  { slug: "friend", name: "친구" },
  { slug: "work", name: "직장" },
  { slug: "family", name: "가족" },
  { slug: "club", name: "동아리" },
  { slug: "school", name: "학교" },
  { slug: "client", name: "고객" },
  { slug: "neighbor", name: "이웃" },
  { slug: "mentor", name: "멘토" },
]

const PERSON_SPECS: PersonSpec[] = [
  {
    name: "김지수",
    nickname: "지수",
    gender: "female",
    profile_index: 3,
    avatar_bg: 1,
    relationship_type: "friend",
    phone_number: "01012345678",
    kakao_nickname: "지수🌸",
    instagram_handle: "jisoo.kim",
    birth: [1995, 5, 12],
    mbti: "ENFP",
    food_preference: "매운 음식 안 먹음",
    how_we_met: "대학교 동아리",
    memo: "최근 이직 준비 중. 디자인 스튜디오 인터뷰 봤다고 함.",
    reminder_interval_days: 30,
    last_contact_days_ago: 12,
    tagSlugs: ["friend", "club"],
  },
  {
    name: "이민호",
    nickname: "민호 과장",
    gender: "male",
    profile_index: 5,
    avatar_bg: 4,
    relationship_type: "colleague",
    phone_number: "01098765432",
    kakao_nickname: "이민호 과장",
    birth: [1990, 11, 3],
    mbti: "ISTJ",
    how_we_met: "이전 직장 동료",
    memo: "결혼식 다녀옴. 답례 떡 받음.",
    reminder_interval_days: 60,
    last_contact_days_ago: 45,
    tagSlugs: ["work"],
  },
  {
    name: "엄마",
    nickname: null,
    gender: "female",
    profile_index: 12,
    avatar_bg: 6,
    relationship_type: "family",
    phone_number: "01055555555",
    birth: [1965, 3, 22],
    food_preference: "건강식 좋아하심",
    memo: "건강검진 다녀오심. 무릎이 안 좋다고 함.",
    reminder_interval_days: 7,
    last_contact_days_ago: 3,
    tagSlugs: ["family"],
  },
  {
    name: "아빠",
    nickname: null,
    gender: "male",
    profile_index: 14,
    avatar_bg: 5,
    relationship_type: "family",
    phone_number: "01066666666",
    birth: [1962, 8, 14],
    food_preference: "찌개류 좋아하심",
    memo: "올해 환갑. 가족 여행 계획 중.",
    reminder_interval_days: 7,
    last_contact_days_ago: 5,
    tagSlugs: ["family"],
  },
  {
    name: "박서연",
    nickname: "서연",
    gender: "female",
    profile_index: 6,
    avatar_bg: 2,
    relationship_type: "friend",
    phone_number: "01023456789",
    kakao_nickname: "서연",
    instagram_handle: "seoyeon_park",
    birth: [1996, 7, 21],
    mbti: "INFP",
    food_preference: "비건",
    how_we_met: "대학교 같은 과",
    memo: "요가 강사 자격증 땄음. 다음에 같이 클래스 가기로.",
    reminder_interval_days: 45,
    last_contact_days_ago: 20,
    tagSlugs: ["friend", "school"],
  },
  {
    name: "최준영",
    nickname: "준영",
    gender: "male",
    profile_index: 9,
    avatar_bg: 3,
    relationship_type: "friend",
    phone_number: "01034567890",
    kakao_nickname: "준영",
    instagram_handle: "junyoung.choi",
    birth: [1993, 1, 30],
    mbti: "ENTP",
    how_we_met: "고등학교 동창",
    memo: "최근 창업 관련해서 자주 연락. 아이디어 잘 굴림.",
    reminder_interval_days: 30,
    last_contact_days_ago: 8,
    tagSlugs: ["friend"],
  },
  {
    name: "정혜린",
    nickname: "혜린 선배",
    gender: "female",
    profile_index: 8,
    avatar_bg: 1,
    relationship_type: "colleague",
    phone_number: "01045678901",
    kakao_nickname: "정혜린",
    birth: [1988, 9, 18],
    mbti: "ENTJ",
    how_we_met: "스타트업에서 만남",
    memo: "현재 PM. 멘토링 받기로 약속.",
    reminder_interval_days: 60,
    last_contact_days_ago: 30,
    tagSlugs: ["work", "mentor"],
  },
  {
    name: "한도윤",
    nickname: "도윤",
    gender: "male",
    profile_index: 10,
    avatar_bg: 4,
    relationship_type: "friend",
    kakao_nickname: "도윤이",
    instagram_handle: "doyoon",
    birth: [1994, 12, 5],
    mbti: "ISFP",
    how_we_met: "대학교 동아리",
    memo: "사진 찍는 거 좋아함. 자주 같이 출사 다님.",
    reminder_interval_days: 30,
    last_contact_days_ago: 14,
    tagSlugs: ["friend", "club"],
  },
  {
    name: "유아인",
    nickname: "아인",
    gender: "female",
    profile_index: 17,
    avatar_bg: 6,
    relationship_type: "friend",
    phone_number: "01056789012",
    kakao_nickname: "유아인",
    instagram_handle: "ahin.yu",
    birth: [1995, 4, 8],
    mbti: "ESFJ",
    how_we_met: "교환학생 룸메이트",
    memo: "결혼 준비 중. 청첩장 받음.",
    reminder_interval_days: 21,
    last_contact_days_ago: 10,
    tagSlugs: ["friend"],
  },
  {
    name: "송지훈",
    nickname: "지훈",
    gender: "male",
    profile_index: 19,
    avatar_bg: 2,
    relationship_type: "colleague",
    phone_number: "01067890123",
    kakao_nickname: "송지훈",
    birth: [1992, 6, 25],
    mbti: "INTJ",
    how_we_met: "현 직장 옆 팀",
    memo: "코드리뷰 잘해줌. 가끔 점심 같이 먹음.",
    reminder_interval_days: 60,
    last_contact_days_ago: 7,
    tagSlugs: ["work"],
  },
  {
    name: "조하늘",
    nickname: "하늘",
    gender: "female",
    profile_index: 21,
    avatar_bg: 3,
    relationship_type: "friend",
    kakao_nickname: "하늘🌤️",
    instagram_handle: "ha_neul",
    birth: [1997, 2, 14],
    mbti: "INFJ",
    how_we_met: "독서 모임",
    memo: "신간 읽기 모임 멤버. 다음 모임 책 추천해주기.",
    reminder_interval_days: 45,
    last_contact_days_ago: 22,
    tagSlugs: ["friend"],
  },
  {
    name: "임승우",
    nickname: "승우 형",
    gender: "male",
    profile_index: 23,
    avatar_bg: 5,
    relationship_type: "colleague",
    phone_number: "01078901234",
    kakao_nickname: "임승우",
    birth: [1985, 10, 11],
    mbti: "ESTJ",
    how_we_met: "이전 직장 팀장",
    memo: "이직 후에도 가끔 연락. 결혼 5주년.",
    reminder_interval_days: 90,
    last_contact_days_ago: 70,
    tagSlugs: ["work", "mentor"],
  },
  {
    name: "강민서",
    nickname: "민서",
    gender: "female",
    profile_index: 25,
    avatar_bg: 1,
    relationship_type: "friend",
    kakao_nickname: "강민서",
    instagram_handle: "minseo.k",
    birth: [1996, 11, 28],
    mbti: "ENFJ",
    how_we_met: "대학원 같은 학과",
    memo: "박사 과정 진행 중. 논문 발표 임박.",
    reminder_interval_days: 30,
    last_contact_days_ago: 18,
    tagSlugs: ["friend", "school"],
  },
  {
    name: "윤재현",
    nickname: "재현",
    gender: "male",
    profile_index: 27,
    avatar_bg: 4,
    relationship_type: "friend",
    phone_number: "01089012345",
    kakao_nickname: "재현",
    birth: [1993, 8, 3],
    mbti: "ESFP",
    food_preference: "회 좋아함",
    how_we_met: "대학교 동아리",
    memo: "회사 근처라 종종 점심.",
    reminder_interval_days: 30,
    last_contact_days_ago: 6,
    tagSlugs: ["friend", "club"],
  },
  {
    name: "오수진",
    nickname: "수진 누나",
    gender: "female",
    profile_index: 4,
    avatar_bg: 2,
    relationship_type: "acquaintance",
    kakao_nickname: "오수진",
    birth: [1989, 3, 17],
    mbti: "ISTP",
    how_we_met: "독립서점에서 알게 됨",
    memo: "독서 취향 비슷함. 책 추천 많이 받음.",
    reminder_interval_days: 60,
    last_contact_days_ago: 50,
    tagSlugs: ["friend"],
  },
  {
    name: "장태호",
    nickname: "태호",
    gender: "male",
    profile_index: 11,
    avatar_bg: 3,
    relationship_type: "client",
    phone_number: "01090123456",
    kakao_nickname: "장태호 대표",
    birth: [1980, 5, 9],
    mbti: "ESTP",
    how_we_met: "프리랜서 일감 의뢰",
    memo: "외주 클라이언트. 다음 프로젝트 논의 중.",
    reminder_interval_days: 30,
    last_contact_days_ago: 4,
    tagSlugs: ["client"],
  },
  {
    name: "이서윤",
    nickname: "서윤이",
    gender: "female",
    profile_index: 13,
    avatar_bg: 6,
    relationship_type: "family",
    kakao_nickname: "이서윤",
    instagram_handle: "seoyoon",
    birth: [2000, 6, 30],
    mbti: "ISFJ",
    memo: "사촌 동생. 대학생.",
    reminder_interval_days: 60,
    last_contact_days_ago: 25,
    tagSlugs: ["family"],
  },
  {
    name: "박형준",
    nickname: "형준",
    gender: "male",
    profile_index: 15,
    avatar_bg: 5,
    relationship_type: "friend",
    phone_number: "01001020304",
    kakao_nickname: "박형준",
    birth: [1992, 4, 19],
    mbti: "INTP",
    how_we_met: "직장 동료 → 친구",
    memo: "코딩 친구. 기술 얘기 자주.",
    reminder_interval_days: 30,
    last_contact_days_ago: 11,
    tagSlugs: ["friend", "work"],
  },
  {
    name: "신유나",
    nickname: "유나",
    gender: "female",
    profile_index: 16,
    avatar_bg: 1,
    relationship_type: "friend",
    kakao_nickname: "유나",
    instagram_handle: "yuna.shin",
    birth: [1998, 9, 5],
    mbti: "ENFP",
    how_we_met: "워크샵에서 만남",
    memo: "마케팅 인플루언서. 콜라보 제안 가능.",
    reminder_interval_days: 45,
    last_contact_days_ago: 35,
    tagSlugs: ["friend", "work"],
  },
  {
    name: "권태민",
    nickname: "태민이",
    gender: "male",
    profile_index: 18,
    avatar_bg: 2,
    relationship_type: "friend",
    kakao_nickname: "권태민",
    birth: [1991, 1, 24],
    mbti: "ENTJ",
    how_we_met: "초등학교 친구",
    memo: "오랜 친구. 결혼식 사회 봐줬음.",
    reminder_interval_days: 60,
    last_contact_days_ago: 60,
    tagSlugs: ["friend"],
  },
  {
    name: "남예진",
    nickname: "예진",
    gender: "female",
    profile_index: 20,
    avatar_bg: 4,
    relationship_type: "colleague",
    phone_number: "01005060708",
    kakao_nickname: "남예진",
    birth: [1994, 7, 16],
    mbti: "INFP",
    how_we_met: "현 직장",
    memo: "디자인 팀. 협업 자주.",
    reminder_interval_days: 30,
    last_contact_days_ago: 9,
    tagSlugs: ["work"],
  },
  {
    name: "고은비",
    nickname: "은비",
    gender: "female",
    profile_index: 22,
    avatar_bg: 3,
    relationship_type: "friend",
    instagram_handle: "eun_b_go",
    birth: [1995, 12, 1],
    mbti: "ISFP",
    how_we_met: "여행 중 만남",
    memo: "제주도에서 게스트하우스 운영. 한 번 더 가기로.",
    reminder_interval_days: 90,
    last_contact_days_ago: 80,
    tagSlugs: ["friend"],
  },
  {
    name: "정민혁",
    nickname: "민혁 선배",
    gender: "male",
    profile_index: 24,
    avatar_bg: 5,
    relationship_type: "colleague",
    kakao_nickname: "정민혁 부장",
    birth: [1982, 5, 7],
    mbti: "ESTJ",
    how_we_met: "대기업 시절 사수",
    memo: "이직 멘토. 분기마다 한 번씩 식사.",
    reminder_interval_days: 90,
    last_contact_days_ago: 100,
    tagSlugs: ["work", "mentor"],
  },
  {
    name: "할머니",
    nickname: "외할머니",
    gender: "female",
    profile_index: 26,
    avatar_bg: 6,
    relationship_type: "family",
    phone_number: "01077778888",
    birth: [1940, 4, 3],
    food_preference: "전통 한식",
    memo: "주말마다 안부 전화 드리기.",
    reminder_interval_days: 7,
    last_contact_days_ago: 4,
    tagSlugs: ["family"],
  },
  {
    name: "황지원",
    nickname: "지원",
    gender: "female",
    profile_index: 28,
    avatar_bg: 2,
    relationship_type: "friend",
    kakao_nickname: "황지원",
    instagram_handle: "ji_won_h",
    birth: [1996, 8, 12],
    mbti: "ESTP",
    how_we_met: "헬스장에서 만남",
    memo: "운동 메이트. 주 2회 같이 운동.",
    reminder_interval_days: 14,
    last_contact_days_ago: 5,
    tagSlugs: ["friend"],
  },
  {
    name: "배현우",
    nickname: "현우",
    gender: "male",
    profile_index: 29,
    avatar_bg: 1,
    relationship_type: "client",
    phone_number: "01099887766",
    kakao_nickname: "배현우 매니저",
    birth: [1984, 11, 19],
    mbti: "ISTJ",
    how_we_met: "프리랜스 의뢰",
    memo: "꼼꼼한 클라이언트. 다음 분기 계약 논의.",
    reminder_interval_days: 30,
    last_contact_days_ago: 15,
    tagSlugs: ["client"],
  },
  {
    name: "김다은",
    nickname: "다은",
    gender: "female",
    profile_index: 30,
    avatar_bg: 4,
    relationship_type: "acquaintance",
    instagram_handle: "daeun.k",
    birth: [1997, 10, 22],
    mbti: "ENFP",
    how_we_met: "컨퍼런스에서 명함 교환",
    memo: "스타트업 마케터. 한 번 더 만나서 얘기하기.",
    reminder_interval_days: 60,
    last_contact_days_ago: 55,
    tagSlugs: ["work"],
  },
  {
    name: "옆집 아주머니",
    nickname: "아주머니",
    gender: "female",
    profile_index: 2,
    avatar_bg: 3,
    relationship_type: "acquaintance",
    birth: null,
    food_preference: "직접 만든 김치",
    memo: "옆집. 가끔 반찬 나눠주심.",
    reminder_interval_days: 60,
    last_contact_days_ago: 30,
    tagSlugs: ["neighbor"],
  },
  {
    name: "유성호 교수님",
    nickname: "유 교수님",
    gender: "male",
    profile_index: 7,
    avatar_bg: 5,
    relationship_type: "acquaintance",
    kakao_nickname: "유성호 교수",
    birth: [1970, 2, 11],
    mbti: "INTJ",
    how_we_met: "대학원 지도교수",
    memo: "학회 추천서 받음. 새해 인사 드리기.",
    reminder_interval_days: 120,
    last_contact_days_ago: 200,
    tagSlugs: ["mentor", "school"],
  },
  {
    name: "이건우",
    nickname: "건우",
    gender: "male",
    profile_index: 1,
    avatar_bg: 6,
    relationship_type: "friend",
    kakao_nickname: "건우",
    instagram_handle: "geon.woo",
    birth: [1993, 6, 8],
    mbti: "ISTP",
    how_we_met: "친구의 친구",
    memo: "보드게임 모임 멤버. 매월 모임.",
    reminder_interval_days: 30,
    last_contact_days_ago: 17,
    tagSlugs: ["friend"],
  },
]

export function buildSeed(): Pick<
  GuestState,
  | "persons"
  | "tags"
  | "personTags"
  | "contacts"
  | "reminders"
  | "notes"
  | "events"
  | "gifts"
  | "loans"
  | "scores"
> {
  const now = new Date().toISOString()

  // 태그
  const tagsBySlug = new Map<string, GuestTag>()
  const tags: GuestTag[] = TAG_SPECS.map((t) => {
    const tag: GuestTag = {
      id: uid(),
      name: t.name,
      color: null,
      created_at: now,
    }
    tagsBySlug.set(t.slug, tag)
    return tag
  })

  // 인물
  const persons: GuestPerson[] = PERSON_SPECS.map((spec) => ({
    id: uid(),
    name: spec.name,
    nickname: spec.nickname ?? null,
    photo_url: null,
    gender: spec.gender,
    profile_index: spec.profile_index,
    avatar_bg: spec.avatar_bg,
    relationship_type: spec.relationship_type,
    relationship_label: null,
    phone_number: spec.phone_number ?? null,
    kakao_nickname: spec.kakao_nickname ?? null,
    instagram_handle: spec.instagram_handle ?? null,
    birth_year: spec.birth?.[0] ?? null,
    birth_month: spec.birth?.[1] ?? null,
    birth_day: spec.birth?.[2] ?? null,
    mbti: spec.mbti ?? null,
    food_preference: spec.food_preference ?? null,
    how_we_met: spec.how_we_met ?? null,
    memo: spec.memo ?? null,
    reminder_interval_days: spec.reminder_interval_days,
    last_contact_at:
      spec.last_contact_days_ago != null
        ? daysAgo(spec.last_contact_days_ago)
        : null,
    status: "active",
    business_card_url: null,
    deleted_at: null,
    created_at: now,
    updated_at: now,
  }))

  // 인물-태그
  const personTags: GuestPersonTag[] = []
  PERSON_SPECS.forEach((spec, idx) => {
    for (const slug of spec.tagSlugs) {
      const tag = tagsBySlug.get(slug)
      if (!tag) continue
      personTags.push({
        person_id: persons[idx].id,
        tag_id: tag.id,
        created_at: now,
      })
    }
  })

  // 인물 검색 헬퍼
  const byName = new Map(persons.map((p) => [p.name, p]))
  const get = (name: string): GuestPerson => {
    const p = byName.get(name)
    if (!p) throw new Error(`seed: missing person ${name}`)
    return p
  }

  // 연락 기록 (각 인물 last_contact_at에 1건씩 + 일부는 추가)
  const contacts: GuestContactLog[] = []
  for (const p of persons) {
    if (!p.last_contact_at) continue
    contacts.push({
      id: uid(),
      person_id: p.id,
      channel: p.kakao_nickname ? "kakao" : p.phone_number ? "phone" : "inperson",
      custom_channel: null,
      direction: "outbound",
      occurred_at: p.last_contact_at,
      memo: null,
      created_at: p.last_contact_at,
    })
  }
  // 자주 연락하는 사람들에 추가 기록
  const frequentNames = ["김지수", "엄마", "아빠", "할머니", "최준영", "황지원"]
  for (const name of frequentNames) {
    const p = get(name)
    contacts.push({
      id: uid(),
      person_id: p.id,
      channel: "kakao",
      custom_channel: null,
      direction: "inbound",
      occurred_at: daysAgo(40),
      memo: "안부 인사",
      created_at: daysAgo(40),
    })
  }

  // 메모 (8명에게)
  const noteSpecs: { name: string; body: string; daysAgo: number }[] = [
    {
      name: "김지수",
      body: "다음에 만날 때 추천한 책 빌려주기로 함",
      daysAgo: 20,
    },
    {
      name: "이민호",
      body: "결혼식 답례떡 잘 받음. 답신 카톡 보냈음.",
      daysAgo: 175,
    },
    {
      name: "엄마",
      body: "건강검진 결과 들으러 같이 가기로",
      daysAgo: 4,
    },
    {
      name: "박서연",
      body: "요가 클래스 같이 등록 — 토요일 10시",
      daysAgo: 18,
    },
    {
      name: "최준영",
      body: "창업 아이디어 공유받음. 다음 주 미팅 잡기.",
      daysAgo: 8,
    },
    {
      name: "정혜린",
      body: "PM 멘토링 요청. 다음 달 한 번 점심.",
      daysAgo: 28,
    },
    {
      name: "유아인",
      body: "결혼식 5월 18일 강남 메리어트. 축의금 10만원 준비.",
      daysAgo: 10,
    },
    {
      name: "장태호",
      body: "Q2 프로젝트 견적서 보냈음. 답변 기다리는 중.",
      daysAgo: 4,
    },
  ]
  const notes: GuestNote[] = noteSpecs.map((n) => ({
    id: uid(),
    person_id: get(n.name).id,
    body: n.body,
    pinned: false,
    created_at: daysAgo(n.daysAgo),
    updated_at: daysAgo(n.daysAgo),
  }))

  // 리마인더 (다양한 종류 + 새 필드 활용)
  const minho = get("이민호")
  const yuain = get("유아인")
  const haneul = get("조하늘")
  const halmuni = get("할머니")
  const gunwoo = get("이건우")
  const youProf = get("유성호 교수님")
  const minseo = get("강민서")
  const reminders: GuestReminder[] = [
    {
      id: uid(),
      person_id: yuain.id,
      reminder_type: "event",
      scheduled_at: daysAhead(7),
      repeat_rule: "none",
      channel: "inapp",
      status: "active",
      title: "유아인 결혼식",
      location: "강남 메리어트 그랜드볼룸",
      co_person_ids: [get("박서연").id, get("한도윤").id],
      message: "축의금 10만원 / 정장 챙기기",
      completed_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: uid(),
      person_id: halmuni.id,
      reminder_type: "followup",
      scheduled_at: daysAhead(2),
      repeat_rule: "none",
      channel: "inapp",
      status: "active",
      title: "외할머니 안부 전화",
      location: null,
      co_person_ids: [],
      message: "주말 안부 전화 드리기",
      completed_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: uid(),
      person_id: get("김지수").id,
      reminder_type: "birthday",
      scheduled_at: daysAhead(14),
      repeat_rule: "yearly",
      channel: "kakao",
      status: "active",
      title: "지수 생일",
      location: null,
      co_person_ids: [],
      message: "선물 미리 사두기 (향초 좋아함)",
      completed_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: uid(),
      person_id: minho.id,
      reminder_type: "followup",
      scheduled_at: daysAhead(5),
      repeat_rule: "none",
      channel: "inapp",
      status: "active",
      title: "민호 과장님 점심 약속 잡기",
      location: null,
      co_person_ids: [],
      message: "오랜만에 만나서 근황 듣기",
      completed_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: uid(),
      person_id: minseo.id,
      reminder_type: "event",
      scheduled_at: daysAhead(21),
      repeat_rule: "none",
      channel: "inapp",
      status: "active",
      title: "민서 박사 논문 발표",
      location: "고려대학교 미래관",
      co_person_ids: [get("박서연").id],
      message: "꽃다발 준비. 발표 후 점심.",
      completed_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: uid(),
      person_id: youProf.id,
      reminder_type: "custom",
      scheduled_at: daysAhead(30),
      repeat_rule: "none",
      channel: "inapp",
      status: "active",
      title: "유 교수님 새해 인사",
      location: null,
      co_person_ids: [],
      message: "오랜만에 안부 메일 드리기",
      completed_at: null,
      created_at: now,
      updated_at: now,
    },
    {
      id: uid(),
      person_id: gunwoo.id,
      reminder_type: "event",
      scheduled_at: daysAhead(10),
      repeat_rule: "none",
      channel: "inapp",
      status: "active",
      title: "보드게임 모임",
      location: "홍대 보드게임카페",
      co_person_ids: [get("최준영").id, get("한도윤").id, get("박형준").id],
      message: "이번에는 카탄하기로 약속",
      completed_at: null,
      created_at: now,
      updated_at: now,
    },
    // 지난 일정 (overdue)
    {
      id: uid(),
      person_id: haneul.id,
      reminder_type: "followup",
      scheduled_at: daysAgo(3),
      repeat_rule: "none",
      channel: "inapp",
      status: "active",
      title: "하늘 독서 모임 책 추천",
      location: null,
      co_person_ids: [],
      message: "다음 모임 책 골라서 단톡방에 공유",
      completed_at: null,
      created_at: daysAgo(10),
      updated_at: daysAgo(10),
    },
  ]

  // 경조사 (여러 건)
  const events: GuestEvent[] = [
    {
      id: uid(),
      person_id: minho.id,
      event_type: "wedding",
      occurred_at: daysAgo(180),
      amount: 100_000,
      direction: "sent",
      attended: true,
      location: "강남 메리어트",
      memo: "동기들과 같이 참석",
      created_at: daysAgo(180),
    },
    {
      id: uid(),
      person_id: get("권태민").id,
      event_type: "wedding",
      occurred_at: daysAgo(420),
      amount: 150_000,
      direction: "sent",
      attended: true,
      location: "잠실 롯데호텔",
      memo: "사회 봐줬음",
      created_at: daysAgo(420),
    },
    {
      id: uid(),
      person_id: get("정민혁").id,
      event_type: "funeral",
      occurred_at: daysAgo(90),
      amount: 50_000,
      direction: "sent",
      attended: false,
      location: null,
      memo: "어머니 부고. 카톡으로 조의 표현.",
      created_at: daysAgo(90),
    },
    {
      id: uid(),
      person_id: get("이서윤").id,
      event_type: "birthday",
      occurred_at: daysAgo(150),
      amount: 100_000,
      direction: "received",
      attended: true,
      location: null,
      memo: "사촌 동생 20살 축하금 받음",
      created_at: daysAgo(150),
    },
  ]

  // 선물
  const gifts: GuestGift[] = [
    {
      id: uid(),
      person_id: get("김지수").id,
      direction: "sent",
      kind: "item",
      amount: null,
      item_name: "향초 세트",
      occasion: "생일",
      occurred_at: daysAgo(60),
      notified_at: daysAgo(63),
      linked_event_id: null,
      memo: "지수가 좋아하는 우드 향",
      created_at: daysAgo(60),
    },
    {
      id: uid(),
      person_id: get("엄마").id,
      direction: "received",
      kind: "item",
      amount: null,
      item_name: "용돈",
      occasion: "생일",
      occurred_at: daysAgo(40),
      notified_at: null,
      linked_event_id: null,
      memo: "엄마가 챙겨주신 용돈",
      created_at: daysAgo(40),
    },
    {
      id: uid(),
      person_id: get("박서연").id,
      direction: "sent",
      kind: "item",
      amount: null,
      item_name: "요가매트",
      occasion: "취업 축하",
      occurred_at: daysAgo(120),
      notified_at: daysAgo(125),
      linked_event_id: null,
      memo: "프리미엄 요가 매트",
      created_at: daysAgo(120),
    },
    {
      id: uid(),
      person_id: get("아빠").id,
      direction: "sent",
      kind: "item",
      amount: null,
      item_name: "운동화",
      occasion: "환갑 축하",
      occurred_at: daysAgo(20),
      notified_at: daysAgo(22),
      linked_event_id: null,
      memo: "걷기 좋아하셔서",
      created_at: daysAgo(20),
    },
    {
      id: uid(),
      person_id: get("최준영").id,
      direction: "received",
      kind: "cash",
      amount: 50_000,
      item_name: null,
      occasion: "이사 축하",
      occurred_at: daysAgo(70),
      notified_at: null,
      linked_event_id: null,
      memo: null,
      created_at: daysAgo(70),
    },
  ]

  // 대여
  const loans: GuestLoan[] = [
    {
      id: uid(),
      person_id: get("김지수").id,
      direction: "lent",
      amount: 50_000,
      occurred_at: daysAgo(15),
      due_at: null,
      returned_at: null,
      memo: "택시비 잠깐 빌려줌",
      created_at: daysAgo(15),
    },
    {
      id: uid(),
      person_id: get("최준영").id,
      direction: "lent",
      amount: 200_000,
      occurred_at: daysAgo(60),
      due_at: daysAhead(30),
      returned_at: null,
      memo: "월급일 전 임시 대여",
      created_at: daysAgo(60),
    },
    {
      id: uid(),
      person_id: get("한도윤").id,
      direction: "borrowed",
      amount: 30_000,
      occurred_at: daysAgo(40),
      due_at: null,
      returned_at: daysAgo(20),
      memo: "사진관 출력비. 회수 완료.",
      created_at: daysAgo(40),
    },
  ]

  return {
    persons,
    tags,
    personTags,
    contacts,
    reminders,
    notes,
    events,
    gifts,
    loans,
    scores: [],
  }
}
